version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - json-server

  json-server:
    image: clue/json-server
    volumes:
      - ./src/api/data.json:/data/db.json
    ports:
      - '3001:80'

networks:
  app-network:
    driver: bridge
